name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The semantic version of the new release.
        required: true
        type: string
jobs:
  release:
    name: Release
    uses: brobeson/ActionRelease/.github/workflows/release.yaml@v1
    with:
      version: ${{inputs.version}}
